=== damnyana/XML-Project/book_catalog.dtd
<?xml version="1.0" encoding="UTF-8"?>
  <!ELEMENT book_catalog (book*)>
  <!ELEMENT book (id, book_header, book_details)>

  <!ELEMENT id (#PCDATA)>
  <!ATTLIST id code ID #REQUIRED>

  <!--BOOK HEADER -->
  <!ELEMENT book_header (book_name, price, cover_path)>
  <!ELEMENT book_name (#PCDATA)>
  <!ELEMENT price (#PCDATA)>
  <!ELEMENT cover_path  EMPTY>
  <!ATTLIST cover_path path CDATA #IMPLIED>

  <!--BOOK DETAILS -->
  <!ELEMENT book_details (summary, publish_date?, pages, cover_type, rating?, genres, publisher, language, authors)>
  <!ELEMENT summary (#PCDATA)>
  <!ELEMENT publish_date (date)>
  <!ELEMENT pages (#PCDATA)>
  <!ELEMENT cover_type EMPTY>
  <!ATTLIST cover_type type (soft | hard) #REQUIRED>
  <!ELEMENT rating (#PCDATA)>
  <!ELEMENT genres (genre+)>
  <!ELEMENT genre EMPTY>
  <!ATTLIST genre name (novel|action|comedy|drama|family|foreign|horror|musical|romantic|fantasy|history|modern|science|popular-science|other) #REQUIRED>
  <!ELEMENT language EMPTY>
  <!ATTLIST language name (bulgarian | english | spanish) #REQUIRED>
  <!ELEMENT publisher (#PCDATA)>

  <!--AUTHORS INFO -->
  <!ELEMENT authors (author*)>
  <!ELEMENT author (author_name, biography?, published_books?, nationality?, birth_day?, death_day?)>
  <!ELEMENT author_name (#PCDATA)>
  <!ELEMENT biography (#PCDATA)>
  <!ELEMENT published_books (#PCDATA)>
  <!ELEMENT nationality (#PCDATA)>
  <!ELEMENT birth_day (date)>
  <!ELEMENT death_day (date)>

  <!ELEMENT date EMPTY>
  <!ATTLIST date day CDATA #IMPLIED>
  <!ATTLIST date month CDATA #IMPLIED>
  <!ATTLIST date year CDATA #IMPLIED>

=== damnyana/XML-Project/book_5.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE book_catalog SYSTEM "book_catalog.dtd">
<book_catalog>
    <book>
        <id code="A5"> </id>
        <book_header>
            <book_name>Кратка история на времето</book_name>
            <price>19.99</price>
            <cover_path path="..\images\covers\kratka-istoria-na-vremeto.jpg"/>
        </book_header>
        <book_details>
            <summary>Имало ли е времето начало? Може ли времето да тече назад? Безкрайна ли е Вселената, или е ограничена? Това са само някои от въпросите, разглеждани в този всепризнат шедьовър, който започва с преглед на големите теории за устройството на космоса от Нютон до Айнщайн, преди да навлезе в същността на тайните, които продължават да се крият в сърцето на пространство-времето.</summary>
            <publish_date>
                <date year="2005"/>
            </publish_date>
            <pages>288</pages>
            <cover_type type="soft"/>
            <genres>
                <genre name="popular-science"/>
            </genres>
            <publisher>Бард</publisher>
            <language name="bulgarian"/>
            <authors>
                <author>
                    <author_name>Стивън Хокинг</author_name>
                    <biography>Професор Стивън Уилям Хокинг, CH CBE FRS (на английски: Stephen William Hawking) е английски астрофизик, автор на книги и статии за новите открития и идеи за Вселената и нейното зараждане, включително и на популярната „Кратка история на времето“ (A Brief History of Time, 1988), която му спечелва международна известност.
                    До 2009 г. е Лукасов професор по математика на Кеймбриджкия университет (пост, заеман някога от Исак Нютон[4]). Занимава се основно с космология и квантова механика, известен е и като популяризатор на науката. Въпреки тежкото си заболяване – амиотрофична латерална склероза (АЛС) – Хокинг не престава да се труди в областта на науката, показвайки, че физическото увреждане не прави никого по-малко способен да твори.</biography>
                    <published_books>9</published_books>                    
                    <nationality>британец</nationality>
                    <birth_day>
                         <date day="8" month="1" year="1942"/>
                    </birth_day>
                    <death_day>
                        <date day="14" month="3" year="2018"/>
                    </death_day>
                </author>
            </authors>
        </book_details>
    </book>
</book_catalog>

=== damnyana/XML-Project/test.xml
<?xml version= "1.0"encoding="UTF-8"?>

<!DOCTYPE book_catalog SYSTEM "book_catalog.dtd">
<book_catalog>
    <book>
        <id code="AN"/>
        <book_header>
            <book_name>Book name</book_name>
            <price>price</price>
            <cover_path path="../path"/>
        </book_header>
        <book_details>
            <summary>Summary text</summary>
            <publish_date>
                <date day="2" month="10" year="1989"/>
            </publish_date>
            <pages>234</pages>
            <cover_type type="soft"/>
            <rating>4.44</rating>
            <genres>
                <genre name="action"/>
            </genres>
            <publisher>publisher</publisher>
            <language name="bulgarian"/>
            <authors>
                <author>
                    <author_name>Author name</author_name>
                    <biography>biography</biography>
                    <published_books>published_books</published_books>
                    <nationality>nationality</nationality>
                    <birth_day>
                        <date day="23" month="5" year="1987"/>
                    </birth_day>
                </author>
            </authors>
        </book_details>
    </book>
</book_catalog>

=== damnyana/XML-Project/book_2.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE book_catalog SYSTEM "book_catalog.dtd">
<book_catalog>
    <book>
        <id code="A2"> </id>
        <book_header>
            <book_name>1984</book_name>
            <price>24.00</price>
            <cover_path path="..\images\covers\1984.jpg"/>
        </book_header>
        <book_details>
            <summary>Уинстън Смит работи в Министерството на истината в Лондон, град от държавата Океания. Неговото служебно задължение е да пренаписва новини от стари вестници, за да станат в съответствие с представяните от установената власт исторически факти, защото: „Който владее миналото, той владее и бъдещето. Който владее настоящето, владее миналото”</summary>
            <publish_date>
                <date day="8" month="6" year="1949"/>
            </publish_date>
            <pages>316</pages>
            <cover_type type="hard"/>
            <rating>5.50</rating>
            <genres>
                <genre name="novel"/>
            </genres>
            <publisher>Фама+</publisher>
            <language name="bulgarian"/>
            <authors>
                <author>
                    <author_name>Джордж Оруел</author_name>
                    <biography>Ерик Артър Блеър (на английски: Eric Arthur Blair; известен под псевдонима Джордж Оруел, на английски: George Orwell) е британски писател, журналист и поет. Той е сред най-уважаваните английски есеисти на ХХ век, талантлив и опитен романист. Творбите му са пропити с интелигентност, дълбока загриженост за социалната несправедливост, силна опозиция на тоталитаризма, страст към чистота на езика и вяра в демократичния социализъм. Най-популярен е с двата си романа, написани към края на краткия му живот: „Фермата на животните“ и „1984“. </biography>
                    <published_books>28</published_books>
                    <nationality>британец</nationality>
                    <birth_day>
                         <date day="25" month="6" year="1903"/>
                    </birth_day>
                    <death_day>
                        <date day="21" month="1" year="1950"/>
                    </death_day>
                    </author>
            </authors>
        </book_details>
    </book>
</book_catalog>

=== damnyana/XML-Project/book_1.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE book_catalog SYSTEM "book_catalog.dtd">
<book_catalog>
    <book>
        <id code="A1"> </id>
        <book_header>
            <book_name>Жътварят</book_name>
            <price>9.00</price>
            <cover_path path="..\images\covers\zhatvaryat-30.jpg"/>
        </book_header>
        <book_details>
            <summary>Смърт го няма - смятат го за... хъм... изчезнал. А това причинява хаоса, който е задължителен след прекратяване на особено важна комунална услуга. Светът на Диска вече гъмжи от призраци и полтъргайсти. Активистът за правата на мъртъвците Рег Шу (един от девизите му гласи: "Защо търпите да ходят по вас?") изведнъж има повече работа, отколкото някога си е мечтал. А току-що починалият Уиндъл Пунс се събужда в ковчега и установява, че се е върнал към живота във вид на труп. И ето - на Уиндъл и не особено плашещата групичка неумрели в Анкх-Морпорк се пада мисията да опазят света на живите. През това време в малка ферма далеч, много далеч от града един висок мрачен непознат се оказва много сръчен с коса в ръцете. Има реколта за прибиране в хамбарите. И едно твърде странно единоборство за спечелване.</summary>
            <publish_date>
                <date year="1991"/>
            </publish_date>
            <pages>360</pages>
            <cover_type type="soft"/>
            <rating>5.60</rating>
            <genres>
                <genre name="fantasy"/>
            </genres>
            <publisher>Вузев</publisher>
            <language name="bulgarian"/>
            <authors>
                <author>
                    <author_name>Тери Пратчет</author_name>
                    <biography>Сър Тери Пратчет е британски писател, най-продаваният автор във Великобритания през 1990-те години. Най-известен е със серията си от комични фентъзи романи за Света на Диска. До декември 2007 г. е продал 55 милиона книги по света с преводи на 36 езика. Пратчет е вторият най-четен автор във Великобритания и седмият най-четен неамерикански автор в САЩ.</biography>
                    <published_books>104</published_books>
                    <nationality>британец</nationality>
                    <birth_day>
                         <date day="28" month="4" year="1948"/>
                    </birth_day>
                    <death_day>
                        <date day="12" month="3" year="2015"/>
                    </death_day>
                    </author>
            </authors>
        </book_details>
    </book>
</book_catalog>

=== damnyana/XML-Project/book_3.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE book_catalog SYSTEM "book_catalog.dtd">
<book_catalog>
    <book>
        <id code="A3"> </id>
        <book_header>
            <book_name>Хари Потър и Философският камък</book_name>
            <price>19.90</price>
            <cover_path path="..\images\covers\hari-potar-i-filosofskiyat-kamak-31.jpg"/>
        </book_header>
        <book_details>
            <summary>Представете си, че до 10-та си години сте живели под стълбите при семейство, което ви мрази. И на 11-я си рожден ден откривате, че сте истински магьосник! Запознайте се Хари Потър... Едно удивително приключение е на път да започне.</summary>
            <publish_date>
                <date year="2016"/>
            </publish_date>
            <pages>280</pages>
            <cover_type type="hard"/>
            <rating>5.80</rating>
            <genres>
                <genre name="fantasy"/>
            </genres>
            <publisher>Егмонт</publisher>
            <language name="bulgarian"/>
            <authors>
                <author>
                    <author_name>Дж. К. Роулинг</author_name>
                    <biography>ДЖ. К. РОУЛИНГ е автор на поставилата множество рекорди и спечелила голям брой награди поредица за Хари Потър. Обичани от феновете по света, книгите ѝ са продадени в над 500 милиона екземпляра, преведени са на 80 езика и са превърнати в 8 хитови филма. Пише и три допълнителни издания в помощ на благотворителни кампании – „Куидичът през вековете“, „Фантастични животни и къде да ги намерим“ (в помощ на Comic Relief и Lumos) и „Приказките на барда Бийдъл“ (в помощ на Lumos),
                             както и филмов сценарий, вдъхновен от „Фантастични животни и къде да ги намерим“. Работи и по пиесата Harry Potter and the Cursed Child Parts One and Two с премиера през лятото на 2016 г. в Уест Енд ъф Лондон. През 2012 г. Дж. К. Роулинг стартира Pottermore – дигитална платформа с нови истории за любимите герои на феновете. Дж. К. Роулинг е автор и на роман за възрастни, „Вакантен пост“, като пише и криминални романи под псевдонима Робърт Галбрейт. Носител е на Ордена на британската империя за заслуги в детската литература, на френския Орден на почтения легион и на наградата „Ханс Кристиан Андерсен“.</biography>
                    <published_books>22</published_books>
                    <nationality>британка</nationality>
                    <birth_day>
                         <date day="31" month="6" year="1965"/>
                    </birth_day>
                </author>
            </authors>
        </book_details>
    </book>
</book_catalog>

=== damnyana/XML-Project/book_4.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE book_catalog SYSTEM "book_catalog.dtd">
<book_catalog>
    <book>
        <id code="A4"> </id>
        <book_header>
            <book_name>Майстора и Маргарита</book_name>
            <price>20</price>
            <cover_path path="..\images\covers\maistora-i-margarita.jpg"/>
        </book_header>
        <book_details>
            <summary>Един ден дяволът отива на посещение в Москва, за да проучи как се развива човечеството и как му се отразява съветският строй. С помощта на своята свита - двама демони, млада вещица и огромен черен котарак - той си прави с гражданството фантасмагорични шеги и го подлага на смеховити изпитания. Когато напуска земята, психиатричните заведения са пълни, а силите на реда са в смут... 
            Близо две хиляди години по-рано, в Юдея, римският прокуратор е принуден да потвърди смъртната присъда на един беден скитник философ, който изповядва странното убеждение, че всички хора са добри... Един московски историк пише роман за Пилат Понтийски и среща голямата, непобедима и извънвременна любов...
            Трите линии - сатиричната, трагичната и романтичната - са преплетени виртуозно и изграждат една от най-великите и обичани творби в световната литература. Завършен по времето на сталинските чистки, романът е публикуван за първи път едва през 1966 година, и то съкратен от цензурата с над сто страници. Днес вече е в пълния си вид и популярността му не спира да расте.</summary>
            <publish_date>
                <date year="2011"/>
            </publish_date>
            <pages>430</pages>
            <cover_type type="hard"/>
            <rating>5.70</rating>
            <genres>
                <genre name="fantasy"/>
                <genre name="novel"/>
            </genres>
            <publisher>Фама</publisher>
            <language name="bulgarian"/>
            <authors>
                <author>
                    <author_name>Михаил Булгаков</author_name>
                    <biography>Михаѝл Афана̀сиевич Булга̀ков (на руски: Михаил Афанасьевич Булгаков) е руски писател и драматург. 
                    Роден през 1891 година в руско семейство от средната класа в Киев, през 1916 година завършва медицина в Киевския университет. В годините на Първата световна война и Гражданската война работи като лекар в различни части на страната. След като не успява да емигрира, той се опитва да се приспособи към болшевишкия режим, като през 1921 година се установява в Москва с намерението да се занимава с литература.</biography>
                    <nationality>руснак</nationality>
                    <birth_day>
                         <date day="3" month="5" year="1891"/>
                    </birth_day>
                    <death_day>
                        <date day="10" month="3" year="1940"/>
                    </death_day>
                </author>
            </authors>
        </book_details>
    </book>
</book_catalog>
